# this file controls the IMU only.
#
# it'd also work for any wheel odometry sensors (to see how much we've "really"
# moved), but we don't have those as of writing!

/**:
  ros__parameters:
    # behavior
    two_d_mode: true
    publish_tf: true

    # frame parameters
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # debug logging
    print_diagnostics: true
    debug: false
    debug_out_file: rl_ekf_filter_node_odom.log

    # configure imu for local usage
    imu0: /sensors/depth_image/imu
    imu0_config:
      [
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
      ]

    imu0_differential: false
    imu0_queue_size: 50
    # `false` if the imu reports "raw" acceleration.
    #
    # that means `az` will include gravity
    imu0_remove_gravitational_acceleration: false

    # this is commented out since `/diff_drive_controller/odom` isn't
    # integrated with any actual wheel sensors... which we don't have.
    #
    # if we get them in the future, or can't seem to get things working right,
    # try uncommenting it!
    #
    # odom0: /diff_drive_controller/odom
    # odom0_differential: false
    # odom0_relative: false
    # odom0_queue_size: 10
    # odom0_config:
    #   [
    #     false,
    #     false,
    #     false,
    #     false,
    #     false,
    #     false,
    #     true,
    #     false,
    #     false,
    #     false,
    #     false,
    #     true,
    #     false,
    #     false,
    #     false,
    #   ]

    # the ZED 2i provides "visual" odometry. we can use that here:
    odom0: /sensors/depth_image/odom
    odom0_config: [
        true,
        true,
        false, # Use x, y position
        false,
        false,
        true, # Use yaw orientation
        true,
        true,
        false, # Use vx, vy velocity
        false,
        false,
        true, # Use vyaw angular velocity
        false,
        false,
        false, # Don't use acceleration from odometry
      ]
    odom0_differential: false
    odom0_queue_size: 10
